# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7484ad984031cf1381d2fcbc7e135c2a55ff93a4cce7e85ff08d141effbeba1f87d04ee4a646a1be9f6fd84d5b4431299b09f620a610bd65fb4714ce5c534062

test:
  secret_key_base: e05a9c8284cc9270a8efbd0a089d55e3080b9550ee8ddea17a95eac2af912aea76d106f93b3b1156f7319514c484e76a3e4094e8f8fcb0279fdb97a808cb91be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
