# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d61ed7964f4bcb5d1c5d21c14c04970cba2a8b5164cd624dabbea3aaa83544b1c08f05329551c718dbff54dd432ec9e3b6ba75d2af0b778a9c0c7256a48117

test:
  secret_key_base: 617c38cda3be5c2245830af6c194b0e73851bf75dbd742f13ef17e987b0ccb5e18d3292776030cb5d55a3952fc570119fbd360983858f3b536844ab3f2822b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
