# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5159e1485f59e3903a6e116d6a77161cca20974a12710eedf183f442155b96f1fbc14442e2158e207ba20a544d21f6da1c95873520314e102e35ebb8459dc869

test:
  secret_key_base: 435bd5ec1db32e3ec6670f6b3a83dde7e8be664cbd412f8649f43d36d45603f3d78aaa54ea21abf9909d167df1726368db96782a662cadd8c716efc3937bf56a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
