# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8f539c07f0d0abb8d33f0462a96a80259eacd1183c0bf2a72ac23d8252a0d4dacb6c7b97ac2ce7c2bc0cd80545cd92c7cea4cb8ddd8d818c0233e0cc87d64e

test:
  secret_key_base: 621df3f6a46154f4d31af25ca1b2c1efea6178c56876523438d3c9187838e052d5ddf55f1bde4bd974bfb68acb33868272c3611eba3c3c26b51dc5ba2c2fb816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
