# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82780ec7bbfd41c2aa943ca9e184a46a49caab7ca4cf5283a7cfeae667442b951103a169ecb5993e7cbdd48fd2569a45fbed65f6b3a454a80f0fe22ddd8d78a7

test:
  secret_key_base: 1c29b36fd0ee38060487f5d4c71196a674338e571e3febf372a8a424a04514ee8f97866c6ca621920b2559c78e1a361bf610c4c523030bce9862826d02f4fa18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
